### ISSUE TITLE
Ignore missing registers

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svdtools#67]
My question is about this check:
https://github.com/stm32-rs/svdtools/blob/d8521cd0dc0314365097edcac75ccbb1fa19864c/svdtools/patch.py#L1037-L1038

Is it necessary those checks to be hard error?
It is often particular chips don't have some registers. And we need to create individual rule for them which complicates all patch system.
I'd prefer this check be just warning saying "Rule ignored: register not found". Or something like this.

**Comment by adamgreig** [comment]
Yea, maybe we could have a "-v" verbose mode that prints those errors, and otherwise they are silently ignored. For example we don't have any error at the moment if you try to delete something that doesn't exist, so it's not like we're consistent here anyway.

Having the verbose mode helps when trying to find out why your patch is not working, but we probably don't need the warning the rest of the time.
